"""
    current_pkg() -> PackageSpec

Get the current package specification from the active Pkg environment.

This is a more flexible version of `current_pkg_name` from `TestEnv` that returns
the full `PackageSpec` object rather than just the package name. This provides
access to additional package metadata needed by TestPicker.
"""
function current_pkg()
    ctx = Context()
    ctx.env.pkg === nothing &&
        throw(TestEnvError("trying to activate test environment of an unnamed project"))
    return ctx.env.pkg
end

"Macros whose expansion records exactly one leaf `Test.Result` (`Pass`/`Fail`/`Error`/`Broken`)."
const TEST_RECORDING_MACROS = Set([
    Symbol("@test"),
    Symbol("@test_throws"),
    Symbol("@test_broken"),
    Symbol("@test_skip"),
    Symbol("@test_warn"),
    Symbol("@test_nowarn"),
    Symbol("@test_logs"),
    Symbol("@test_deprecated"),
])

"""
    count_expected_tests(ex) -> Int

Statically count how many [`TEST_RECORDING_MACROS`](@ref) calls occur in `ex`, recursing
into nested `@testset`s, loops, conditionals, etc.

This is a *prediction*, used to size the progress bar before a run starts, not an exact
count: a `@test` inside a runtime loop or generated by another macro's expansion is
counted once no matter how many times it actually executes.
"""
function count_expected_tests(ex)::Int
    ex isa Expr || return 0
    if ex.head === :macrocall
        name = ex.args[1]
        name isa GlobalRef && (name = name.name)
        name isa Symbol && name in TEST_RECORDING_MACROS && return 1
    end
    return sum(count_expected_tests, ex.args; init=0)
end

"""
    count_expected_tests_in_file(file::AbstractString) -> Int

Parse `file` with `JuliaSyntax` and count the expected number of tests it contains, per
[`count_expected_tests`](@ref).

Used for whole test-file runs, where the executed expression is just `include(file)` and
so gives no visibility into the tests it will run.
"""
function count_expected_tests_in_file(file::AbstractString)::Int
    ex = JuliaSyntax.parseall(Expr, read(file, String); filename=file)
    return count_expected_tests(ex)
end
